@baseUrl = http://localhost:5105

GET {{baseUrl}}/health
Accept: application/json

###

GET {{baseUrl}}/api/batches
Accept: application/json

###

POST {{baseUrl}}/api/batches
Content-Type: application/json

{
  "batchNumber": "GL-2026-010",
  "productName": "CBD Gummies 20ct",
  "cultivarName": "Calm River",
  "actorUserId": "db71fe67-2784-45f7-bc1f-20ff7d8f9cf7"
}

###

POST {{baseUrl}}/api/batches/321ca2a0-5241-41f4-bf0a-b27c083c2436/movements
Content-Type: application/json

{
  "toStage": "Released",
  "actorUserId": "2b0472a8-7f72-4001-afd9-f01684099b54",
  "notes": "Shipment left the facility."
}

###

PATCH {{baseUrl}}/api/batches/575cfaf6-54bb-491f-a3d8-adb32a974972/status
Content-Type: application/json

{
  "status": "Active",
  "actorUserId": "df35536a-bd8d-4c84-9bc4-38f895a6828c",
  "reason": "Investigation completed and lot resumed."
}

###

GET {{baseUrl}}/api/batches/321ca2a0-5241-41f4-bf0a-b27c083c2436/documents
Accept: application/json

###

GET {{baseUrl}}/api/users
Accept: application/json

###

GET {{baseUrl}}/api/batches/b0baf409-6994-43b2-adc3-2595dbecee31/audit
Accept: application/json
